create table BOARD(
ID INTEGER not null primary key,
GAME_ID INTEGER not null,
PIT INTEGER not null,
PLAYER_SIDE VARCHAR(15)  not null,
TOKEN_COUNT INTEGER not null,
KALAH BOOLEAN not null,
CREATION_DATE TIMESTAMP not null,
UPDATE_DATE TIMESTAMP,
CONSTRAINT BOARD_GAME_ID_FK foreign key (GAME_ID) references GAME(ID)
);

create unique index BOARD_UNIQUE_INDEX_1 ON BOARD(PIT, GAME_ID);

create index BOARD_INDEX_1 ON BOARD(GAME_ID);